name: cicd
on: 
  push: 
    branches:
    - '*'      # matches every branch that doesn't contain a '/'
    - '*/*'    # matches every branch containing a single '/'
    - '**'     # matches every branch
    - '!main'  #excludes main
 
jobs:
  CICD:
    name: CICD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13'
      - name: installing
        run: 
          npm install
      - name: build
        run:
          npm run build
      - name: test
        run: 
          npm run testonce
     