name: cicd
on: 
  push:
#    branches:
#    - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18'
      - run: 
          npm install
      - run:
          npm run deploy
