name: master-cicd
on: 
  push:
    branches:
    - main
jobs:
  Master-CICD:
    name: Master-CICD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13'
      - name: installing
        run: 
          npm install
      - name: build
        run:
          npm run build
      - name: test
        run: 
          npm run testonce
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: vienna.elric@gmail.com
          build_dir: build
        
