name: cicd
on: 
  push:
#    branches:
#    - main
jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18'
      - name: installing
        run: 
          npm install
      - name: test
        run: 
          npm run testonce
      - name: setupbotuser
        run: |
          git config --global user.email "vienna.elric@gmail.com"
      - name: deploy
        run:
          npm run deploy
        
